//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public int IdAlerta { get; set; }
        public int TotalDefectosUltHora { get; set; }
        public int TotalDefectosUltReinicio { get; set; }
        public string Color { get; set; }
        public int IdModelo { get; set; }
        public int IdDefecto { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual Defecto Defecto { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
