//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JornadaLaboral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JornadaLaboral()
        {
            this.OrdenProduccion = new HashSet<OrdenProduccion>();
            this.Registro = new HashSet<Registro>();
        }
    
        public int IdJornadaLaboral { get; set; }
        public Nullable<int> IdTurno { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public Nullable<int> TotalPrimera { get; set; }
        public Nullable<int> TotalSegunda { get; set; }
        public Nullable<int> TotalHermanado { get; set; }
        public Nullable<System.TimeSpan> HoraRegistro { get; set; }
        public Nullable<int> IdDefecto { get; set; }

        public virtual Turno Turno { get; set; }
        public virtual Defecto Defecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenProduccion> OrdenProduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro> Registro { get; set; }
    }
}
