//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeloColor
    {
        public int IdModeloColor { get; set; }
        public Nullable<int> IdModelo { get; set; }
        public Nullable<int> Codigo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
