//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenProduccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenProduccion()
        {
            this.Registro = new HashSet<Registro>();
        }
    
        public int NumeroOP { get; set; }
        public Nullable<int> NumeroLinea { get; set; }
        public Nullable<int> IdModelo { get; set; }
        public Nullable<int> Codigo { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdJornadaLaboral { get; set; }
        public Nullable<int> SupervisorLinea { get; set; }
        public Nullable<int> SupervisorCalidad { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual JornadaLaboral JornadaLaboral { get; set; }
        public virtual Linea Linea { get; set; }
        public virtual Modelo Modelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro> Registro { get; set; }
    }
}
