//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int IdRegistro { get; set; }
        public Nullable<int> NumeroOP { get; set; }
        public Nullable<int> IdJornadaLaboral { get; set; }
        public Nullable<int> TotalPrimera { get; set; }
        public Nullable<int> TotalSegunda { get; set; }
        public Nullable<int> TotalHermanado { get; set; }
        public Nullable<int> TotalDefectosR { get; set; }
        public Nullable<int> TotalDefectosO { get; set; }
    
        public virtual JornadaLaboral JornadaLaboral { get; set; }
        public virtual OrdenProduccion OrdenProduccion { get; set; }
    }
}
